version: '3.9'
services:
  webserver:
    container_name: PHP1
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./laravel9:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysql1
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ale3
      # MYSQL_USER: root
      # MYSQL_PASSWORD: secret
    volumes:
      - ./laravel9/mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: phpmyadmin1
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysqldb
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysqldb
      MYSQL_ROOT_PASSWORD: secret